### ISSUE TITLE
[Feature]: Show Events on Profile detail page

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/community-platform#288]
only published
- speaker + participant + organizer
- only root/parent event from event

**Comment by phollome** [comment]
for now only visible for logged in user

**Comment by nac62116** [comment]
- show events where profile owner is on waiting list?

**Comment by nac62116** [comment]
- where { published: true } cannot be included in the include statement:
- Either refactor getProfileByUsername() with select instead of include ( all fields must be selected explicitly / query must be extended for future profile fields)
- Or (What i do for now) events get filtered in the code ( events.filter((event) => event.published === true) )
